=== MicheleMacagno/Assignment3/xsd/nffgVerifier.xsd
<?xml version="1.0"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/nffgVerifier" 
	xmlns:tns="http://www.example.org/nffgVerifier" 

	elementFormDefault="qualified">

	<xsd:element name="nffgs" type="tns:XNffgs">
		<xsd:key name="nffg_name">
			<xsd:selector xpath="tns:nffg" />
			<xsd:field xpath="tns:name" />
		</xsd:key>
	</xsd:element>

	<xsd:element name="nffg" type="tns:XNffg" />
	<xsd:element name="policy" type="tns:XPolicy" />
	<xsd:element name="policies" type="tns:XPolicies"/>
	<!-- 	<xsd:element name="verification" type="XVerificationRequest"/> -->
	<!--  this can be useful to verify many policies at a time -->

	
	<xsd:complexType name="XNffgs">
		<xsd:sequence>
			<xsd:element name="nffg" type="tns:XNffg" maxOccurs="unbounded">

				<xsd:key name="node_name">
					<xsd:selector xpath="tns:nodes/tns:node" />
					<xsd:field xpath="tns:name" />
				</xsd:key>


				<!-- 	enforce uniqueness of link names inside a nffg -->
				<xsd:key name="link_name">
					<xsd:selector xpath="tns:links/tns:link" />
					<xsd:field xpath="tns:name" />
				</xsd:key>


				<xsd:keyref name="ref_link_src_node" refer="tns:node_name">
					<xsd:selector xpath="tns:links/tns:link" />
					<xsd:field xpath="tns:src" />
				</xsd:keyref>

				<xsd:keyref name="ref_link_dst_node" refer="tns:node_name">
					<xsd:selector xpath="tns:links/tns:link" />
					<xsd:field xpath="tns:dst" />
				</xsd:keyref>

			</xsd:element>
			</xsd:sequence>
	</xsd:complexType>


	<!-- nffg element declaration -->
	<xsd:complexType name="XNffg">
		<xsd:sequence>
			<xsd:element name="name" type="tns:XNameType" />
			<xsd:element name="lastUpdate" type="xsd:dateTime" />
			<xsd:element name="nodes" type="tns:XNodes" />
			<xsd:element name="links" type="tns:XLinks" />
		</xsd:sequence>
	</xsd:complexType>

<!-- 	Container for all nodes of the Nffg -->
	<xsd:complexType name="XNodes">
		<xsd:sequence>
			<xsd:element name="node" minOccurs="2" maxOccurs="unbounded"
				type="tns:XNode" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- Node declaration -->
	<xsd:complexType name="XNode">
		<xsd:sequence>
			<xsd:element name="name" type="tns:XNameType" />
			<xsd:element name="functionality" type="tns:XFunctionality" />
		</xsd:sequence>

	</xsd:complexType>

	<!-- Functionalities declaration -->
	<xsd:simpleType name="XFunctionality">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="FW" />
			<xsd:enumeration value="DPI" />
			<xsd:enumeration value="NAT" />
			<xsd:enumeration value="SPAM" />
			<xsd:enumeration value="CACHE" />
			<xsd:enumeration value="VPN" />
			<xsd:enumeration value="WEB_SERVER" />
			<xsd:enumeration value="WEB_CLIENT" />
			<xsd:enumeration value="MAIL_SERVER" />
			<xsd:enumeration value="MAIL_CLIENT" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Container for the set of all links -->
	<xsd:complexType name="XLinks">
		<xsd:sequence>
			<xsd:element name="link" minOccurs="1" maxOccurs="unbounded"
				type="tns:XLink" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- Link declaration -->
	<xsd:complexType name="XLink">
		<xsd:sequence>
			<xsd:element name="name" type="tns:XNameType" />
			<xsd:element name="src" type="tns:XNameType" />
			<xsd:element name="dst" type="tns:XNameType" />
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- A set of policies of a given Nffg -->
	<xsd:complexType name="XPolicies">
		<xsd:sequence>
			<xsd:element name="policy" minOccurs="0" maxOccurs="unbounded"	type="tns:XPolicy" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- policy declaration -->
	<xsd:complexType name="XPolicy">
		<xsd:sequence>
			<xsd:element name="name" type="tns:XNameType" />

			<!--imposed the result not mandatory, can be computed, right? -->
			<xsd:element name="positivity" type="xsd:boolean" />
			<xsd:element name="src" type="tns:XNameType" />
			<xsd:element name="dst" type="tns:XNameType" />
			<xsd:element minOccurs="0" maxOccurs="1" name="traversal" type="tns:XTraversal" />

			<!-- The element of the verification, include the result of verification, 
				the date/time and a message with further information -->

			<xsd:element name="verification" type="tns:XVerification"
				minOccurs="0" maxOccurs="1" />

		</xsd:sequence>
 		<!-- 		Added for Assignment3 - the reference for the nffg name  -->
		<xsd:attribute name="nffg" type="tns:XNameType"> </xsd:attribute>
	</xsd:complexType>



	<!-- Traversal policy type definition as extension of reachability property -->
	<xsd:complexType name="XTraversal">
				<xsd:sequence>
					<xsd:element name="functionality" type="tns:XFunctionality"
						minOccurs="1" maxOccurs="unbounded" />
				</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="XVerification">
		<xsd:sequence>
			<xsd:element name="verificationTime" type="xsd:dateTime" />
			<xsd:element name="result" type="xsd:boolean" />
			<xsd:element name="message" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	
<!-- 	<xsd:complexType name="XVerificationRequest"> -->
<!-- 		<xsd:sequence> -->
<!-- 			<xsd:element name="policyname" type="XNameType" minOccurs="1" maxOccurs="unbounded"/> -->
<!-- 		</xsd:sequence> -->
<!-- 	</xsd:complexType> -->
	

	<!-- name - the name of the NF-FG to get (a string made of alphanumeric 
		characters only, where the first character is alphabetic). -->
	<xsd:simpleType name="XNameType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== MicheleMacagno/Assignment3/xsd/policies.xml
<?xml version="1.0"?>
<policies xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:noNamespaceSchemaLocation="nffgVerifier.xsd">
		<policy nffg="nffg1">
			<name>policy1</name>
			<positivity>true</positivity>
			<src>nodopluto1</src>
			<dst>nodos1</dst>
			<verification>
				<verificationTime>2016-07-21T21:00:00.000+02:00</verificationTime>
				<result>true</result>
				<message>This policy is Verified</message>
			</verification>
		</policy>
		
		<policy nffg="nffg2">
			<name>PolicyTraversal1</name>
			<positivity>true</positivity>
			<src>nodos1</src>
			<dst>nodoprova1</dst>
			<traversal>
				<functionality>DPI</functionality>
			</traversal>
		</policy>
	</policies>

=== MicheleMacagno/Assignment3/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<nffgs 
	xmlns="http://www.example.org/nffgVerifier" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/nffgVerifier nffgVerifier.xsd ">


	<nffg href="http://localhost:8080/NffgService/rest/nffg/nffg1">
		<name>nffg1</name>
		<lastUpdate>2015-07-21T21:00:00.000+02:00</lastUpdate>
	<nodes>
		<node>
			<name>nodo1</name>
			<functionality>FW</functionality>
		</node>
		
		<node>
			<name>nodo2</name>
			<functionality>FW</functionality>
		</node>

		<node>
			<name>nodo3</name>
			<functionality>NAT</functionality>
		</node>

		<node>
			<name>nodo4</name>
			<functionality>DPI</functionality>
		</node>

		<node>
			<name>nodo5</name>
			<functionality>DPI</functionality>
		</node>

		<node>
			<name>nodo6</name>
			<functionality>DPI</functionality>
		</node>
	</nodes>
	<links>
		<link>
			<name>link1</name>
			<src>nodo1</src>
			<dst>nodo2</dst>
		</link>

		<link>
			<name>link2</name>
			<src>nodo1</src>
			<dst>nodo3</dst>
		</link>
	</links>
	
	</nffg>

	<nffg href="http://localhost:8080/NffgService/rest/nffg/nffg2">
		<name>nffg2</name>
		<lastUpdate>2015-07-21T21:00:00.000+02:00</lastUpdate>
	<nodes>
	
		<node>
			<name>nodo1</name>
			<functionality>FW</functionality>
		</node>

		<node>
			<name>nodo2</name>
			<functionality>NAT</functionality>
		</node>

		<node>
			<name>nodo3</name>
			<functionality>DPI</functionality>
		</node>

		<node>
			<name>nodo4</name>
			<functionality>DPI</functionality>
		</node>

		<node>
			<name>nodo5</name>
			<functionality>DPI</functionality>
		</node>
	</nodes>
	<links>
		<link>
			<name>link1</name>
			<src>nodo1</src>
			<dst>nodo5</dst>
		</link>

		<link>
			<name>link2</name>
			<src>nodo2</src>
			<dst>nodo3</dst>
		</link>
	</links>

	</nffg>
</nffgs>
